### ISSUE TITLE
Weird error: unable to parse the Dot graph

### ISSUE THREAD

**Issue by Saransh-cpp** [gallais/dot-analysis#1]
I was trying out this repository locally, and the dot files available in `examples/` work great, but running `dot-analysis` on a dot file generated using `cd agda-stdlib; ./graph.sh README.agda` gave me a weird error. I have never used graphviz or dot before, so this might be something stupid.

## Error

I see that there is a missing closing bracket, but I cannot seem to find the extra bracket, nor did I touch the programmatically generated dot file.

```
saransh@Saranshs-MacBook-Air agda-stdlib % dot-analysis _build/README.dot 
dot-analysis: Error when parsing Dot code:
Unable to parse the Dot graph; usually this is because of either:
  * Wrong choice of representation: try the Generalised one
  * Wrong choice of node type; try with `DotGraph String`.

The actual parsing error was:
        Not a valid value wrapped in braces.
        Missing closing bracket:
        Not the expected character: }
```

## Full stacktrace and the dot file

https://gist.github.com/Saransh-cpp/ab08b2febf970501230e60a3bea4adeb

---

Could you please help me with this error? Thank you so much!

**Comment by gallais** [comment]
I did not use `graph.sh` to generate the graphs but called Agda directly.
Is it possible that the call to `tred` in the script generates a dot file which
is not strictly compatible with the Dot specification (the one you include
is interleaving the node and edge declarations for instance but I think the
format may insist on having all the nodes first and then all the edges)?

After dinner I will look into using the more liberal parser the lib provides.

**Comment by Saransh-cpp** [comment]
Ah, `agda -i. -isrc/ --dependency-graph=README.dot README.agda` worked! I think `tred` is the problem here. Please feel free to close this issue. Thanks!

**Comment by JacquesCarette** [comment]
Maybe creating some user instructions with the above would be good to do before closing, so that the next person doesn't encounter the same issue?
